# Generated by Django 3.2.7 on 2021-09-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_score_profile_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='point_origins',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
