# Generated by Django 3.2.7 on 2021-09-28 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210928_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='level',
            new_name='user_level',
        ),
    ]
