# Generated by Django 3.2.7 on 2021-10-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default_user_avatar.jpg', upload_to='user_pics'),
        ),
    ]
