# Generated by Django 3.2.7 on 2021-10-13 13:14

import anime.rename
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default_user_avatar.jpg', upload_to=anime.rename.PathAndRename('user_pics')),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.ImageField(default='default_channel_cover.jpg', upload_to=anime.rename.PathAndRename('user_pics')),
        ),
    ]
