# Generated by Django 3.2.7 on 2021-10-02 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentator',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='post',
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_avatar',
            field=models.ImageField(default='default_channel_avatar.jpg', upload_to='channel_pics'),
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_cover',
            field=models.ImageField(default='default_channel_cover.jpg', upload_to='channel_pics'),
        ),
        migrations.AddField(
            model_name='channel',
            name='created_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='point_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='moderators',
            field=models.ManyToManyField(blank=True, null=True, related_name='moderators', to=settings.AUTH_USER_MODEL),
        ),
    ]
