# Generated by Django 3.2.7 on 2021-10-06 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_subcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcomment',
            name='parent_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.comment'),
        ),
    ]
