# Generated by Django 3.2.7 on 2021-10-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_alter_subcomment_parent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
