# Generated by Django 3.2.7 on 2021-10-13 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_alter_channel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcomment',
            options={'ordering': ['-timestamped']},
        ),
    ]
