# Generated by Django 3.2.7 on 2021-10-13 18:15

import anime.rename
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0015_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_avatar',
            field=models.ImageField(default='default_channel_avatar.jpg', upload_to=anime.rename.PathAndRename('channel_pics')),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_cover',
            field=models.ImageField(default='default_channel_cover.jpg', upload_to=anime.rename.PathAndRename('channel_pics')),
        ),
    ]
