# Generated by Django 3.2.7 on 2021-09-28 07:46

from django.db import migrations, models
import pinax.badges.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointsBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(pinax.badges.base.Badge, models.Model),
        ),
    ]
