# Generated by Django 3.2.7 on 2021-09-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointsBadge',
        ),
    ]
